-- Criação do banco de dados
CREATE DATABASE POWERIQ;

USE POWERIQ;

-- Criação da tabela 'EMPRESA'
CREATE TABLE EMPRESA
    (
        ID INT AUTO_INCREMENT NOT NULL,
        NOME VARCHAR(100) NOT NULL,
        CNPJ VARCHAR(14) UNIQUE NOT NULL,
        ENDERECO VARCHAR(255) NOT NULL,
        SETOR VARCHAR(50) NOT NULL,
        PLANO VARCHAR(20) NOT NULL,

        PRIMARY KEY (ID)
    );
    
-- Criação da tabela 'META'
CREATE TABLE META
	(
		ID INT AUTO_INCREMENT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        DESCRICAO VARCHAR(255) NOT NULL,
        PERCENTUAL_REDUZIR FLOAT NOT NULL,
        STATUS_META VARCHAR(20) NOT NULL,
        
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
	);
    
-- Criação da tabela 'CONSUMO'
CREATE TABLE CONSUMO
	(
		ID INT AUTO_INCREMENT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        CATEGORIA VARCHAR(50) NOT NULL,
        DATA_REGISTRO DATE NOT NULL,
        VALOR_CONSUMO FLOAT NOT NULL,
        CUSTO_CONSUMO DECIMAL(10,2) NOT NULL,
        
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
    );
    
-- Criação da tabela 'FATURA'
CREATE TABLE FATURA
	(
		ID INT AUTO_INCREMENT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        MES_REFERENCIA DATE NOT NULL,
        VALOR_TOTAL DECIMAL(10,2) NOT NULL,
        DATA_EMISSAO DATE NOT NULL,
        
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
    );
    
-- Criação da tabela 'SIMULACAO'
CREATE TABLE SIMULACAO
	(
		ID INT AUTO_INCREMENT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        TIPO_ENERGIA VARCHAR(50) NOT NULL,
        ECONOMIA_ATUAL DECIMAL(10,2) NOT NULL,
        CUSTO_INVESTIMENTO DECIMAL(10,2) NOT NULL,
        RETORNO_INVESTIMENTO INT NOT NULL,
        
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
	);
    
-- Criação da tabela 'NOTIFICACAO'
CREATE TABLE NOTIFICACAO
	(
		ID INT AUTO_INCREMENT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        TIPO_NOTIFICACAO VARCHAR(20) NOT NULL,
        DATA_ENVIO DATE NOT NULL,
        MENSAGEM TEXT NOT NULL,
        
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
	);
